"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['excel-icon.png', 'calendar-icon.png']
OPTIONS = {'iconfile': 'icon.icns',
           'packages': ['screeninfo', 'tkcalendar', 'xlsxwriter']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

